name: screen_retriever_example
description: "Demonstrates how to use the screen_retriever plugin."
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bot_toast: ^4.1.3
  flutter:
    sdk: flutter
  hotkey_manager: ^0.1.8
  screen_retriever:
    # When depending on this package from a real application you should use:
    #   screen_retriever: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.2

flutter:
  uses-material-design: true
